### ISSUE TITLE
Services HTML Formatting

### ISSUE THREAD

**Issue by laurenbeecher** [johnsiwicki/mini-spruce-generator#8]
Generated Services HTML is unformatted, and is displayed over one line. Becomes one very hard to sort through paragraph when moved to CMS. 

Thank you!

**Comment by johnsiwicki** [comment]
I think we have possible fix. We need to try this out https://www.npmjs.com/package/express-beautiful-ejs-engine

**Comment by laurenbeecher** [comment]
Awesome, thanks!

**Comment by chrisroselli** [comment]
Services section removed
